name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        uses: subosito/flutter-action@v2
        user: bluefireteam/flutter-gh-pages@v7
        with:
           baseHref: /SOON_FLAPPY/