name: Gh-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - run: flutter config --enable-web
      - run: flutter build web --release --wasm --base-href="/SOON_FLAPPY/" --dart-define="NAKAMA_SERVER_KEY=${{ secrets.NAKAMA_SERVER_KEY }}"
      - run: git config --global user.name "github-actions"
      - run: git config --global user.email "github-actions@github.com"
      - run: git add build/web --all
      - run: git commit -m "Automatic deployment by GitHub Actions"
      - run: git push origin `git subtree split --prefix build/web main`:gh-pages --force
